{"failures":[],"level":"info","message":"ðŸ§ª Test runner executed on examples/init-examples/basic-example","result":{"failed":0,"ok":1},"timeElapsed":897,"timestamp":"2024-01-27T12:53:22.782Z"}
{"level":"info","message":"ðŸš€ Program executed mainExample.PepitaProgram on examples/run-examples/basic-example","ok":true,"timeElapsed":596,"timestamp":"2024-01-27T12:53:23.506Z"}
{"error":["Error: Fatal error while running validations. Aborting run due to validation errors!","  at validateEnvironment (/home/dodain/workspace/wollok-dev/wollok-ts-cli/src/utils.ts:70:13)","  at buildEnvironmentForProgram (/home/dodain/workspace/wollok-dev/wollok-ts-cli/src/commands/run.ts:262:22)","  at async default_1 (/home/dodain/workspace/wollok-dev/wollok-ts-cli/src/commands/run.ts:51:25)","  at async Context.<anonymous> (/home/dodain/workspace/wollok-dev/wollok-ts-cli/test/run.test.ts:178:7"],"level":"info","message":"ðŸš€ Program executed mainExample.PepitaProgram on examples/run-examples/bad-example","ok":false,"timeElapsed":627,"timestamp":"2024-01-27T12:53:24.138Z"}
{"failures":[],"level":"info","message":"ðŸ§ª Test runner executed on examples/test-examples/normal-case","result":{"failed":0,"ok":2},"timeElapsed":254,"timestamp":"2024-01-27T12:53:26.335Z"}
{"failures":[{"error":["wollok.lib.AssertionException: Expected <2> but found <1>","  at test-two.\"third describe\".\"just a test\" [test-two.wtest:15]"],"test":"test-two.\"third describe\".\"just a test\""}],"level":"info","message":"ðŸ§ª Test runner executed on examples/test-examples/normal-case","result":{"failed":1,"ok":4},"timeElapsed":223,"timestamp":"2024-01-27T12:53:26.562Z"}
{"failures":[],"level":"info","message":"ðŸ§ª Test runner executed on examples/init-examples/basic-example","result":{"failed":0,"ok":1},"timeElapsed":1002,"timestamp":"2024-01-27T12:57:00.341Z"}
{"level":"info","message":"ðŸš€ Program executed mainExample.PepitaProgram on examples/run-examples/basic-example","ok":true,"timeElapsed":688,"timestamp":"2024-01-27T12:57:01.143Z"}
{"error":["Error: Fatal error while running validations. Aborting run due to validation errors!","  at validateEnvironment (/home/dodain/workspace/wollok-dev/wollok-ts-cli/src/utils.ts:70:13)","  at buildEnvironmentForProgram (/home/dodain/workspace/wollok-dev/wollok-ts-cli/src/commands/run.ts:262:22)","  at async default_1 (/home/dodain/workspace/wollok-dev/wollok-ts-cli/src/commands/run.ts:51:25)","  at async Context.<anonymous> (/home/dodain/workspace/wollok-dev/wollok-ts-cli/test/run.test.ts:178:7"],"level":"info","message":"ðŸš€ Program executed mainExample.PepitaProgram on examples/run-examples/bad-example","ok":false,"timeElapsed":639,"timestamp":"2024-01-27T12:57:01.787Z"}
{"failures":[],"level":"info","message":"ðŸ§ª Test runner executed on examples/test-examples/normal-case","result":{"failed":0,"ok":2},"timeElapsed":223,"timestamp":"2024-01-27T12:57:03.958Z"}
{"failures":[{"error":["wollok.lib.AssertionException: Expected <2> but found <1>","  at test-two.\"third describe\".\"just a test\" [test-two.wtest:15]"],"test":"test-two.\"third describe\".\"just a test\""}],"level":"info","message":"ðŸ§ª Test runner executed on examples/test-examples/normal-case","result":{"failed":1,"ok":4},"timeElapsed":228,"timestamp":"2024-01-27T12:57:04.188Z"}
